Refactor directory, update scripts for backend

diff --git a/bin/backend/build-backend b/bin/backend/build-backend
--- a/bin/backend/build-backend
+++ b/bin/backend/build-backend
@@ -12,11 +12,13 @@ if [ "$build" = "prod" ]; then
     echo "===== Build backend-flask-prod image PRODUCTION ENV ====="
     DOCKER_FILE="Dockerfile.prod"
     DOCKER_FILE_NAME="backend-flask-prod"
-
-else
+else if [ "$build" = "dev" ]; then
     echo "===== Build backend-flask image DEVELOPMENT ENV ====="
     DOCKER_FILE="Dockerfile"
     DOCKER_FILE_NAME="backend-flask"
+else
+    echo "===== Input Error, type: <prod> or <dev> ====="
+    exit 1
 fi
 
 docker build \
