fix psql scripts

diff --git a/backend-flask/bin/db/setup b/backend-flask/bin/db/setup
--- a/backend-flask/bin/db/setup
+++ b/backend-flask/bin/db/setup
@@ -1,16 +1,19 @@
-#! /usr/bin/bash -e 
-# stop if it fails at any point
+#! /usr/bin/bash
+set -e # stop if it fails at any point
 
-#echo "==== db-setup"
 CYAN='\033[1;36m'
 NO_COLOR='\033[0m'
 LABEL="db-setup"
 printf "${CYAN}==== ${LABEL}${NO_COLOR}\n"
 
-bin_path="./backend-flask/bin/"
+bin_path="$(realpath .)/bin"
 
 source "$bin_path/db/drop"
+sleep 1
 source "$bin_path/db/create"
+sleep 1
 source "$bin_path/db/schema-load"
+sleep 1
 source "$bin_path/db/seed"
-source "$bin_path/cognito/update_cognito_user_ids"
+sleep 1
+python "$bin_path/cognito/update_cognito_user_ids"
